name: lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  WORKDIR: "."
  RUFF_OUTPUT_FORMAT: github
  UV_FROZEN: "true"
  UV_VERSION: "0.6.0"

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          python-version: "3.10.8"

      - name: Install dependencies
        run: |
          uv pip install -e ".[lint]"

      - name: Run linting
        run: make lint
