name: lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  PYTHON_VERSION: "3.10"
  UV_VERSION: "0.6.0"

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: pip install uv==${{ env.UV_VERSION }}

      - name: Install dependencies
        run: |
          uv pip install -e ".[lint]"

      - name: Run linting
        run: make lint

  test:
    name: Run Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: pip install uv==${{ env.UV_VERSION }}

      - name: Install dependencies
        run: |
          uv pip install -e ".[test]"

      - name: Run unit tests
        run: make test

      - name: Run integration tests
        run: make integration_test
