name: lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  WORKDIR: "."
  RUFF_OUTPUT_FORMAT: github
  UV_FROZEN: "true"
  UV_VERSION: "0.5.25"

jobs:
  build:
    name: "Lint on push or PR"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          python-version: "3.10.8"

      - name: Install dependencies
        run: uv sync --group lint --group typing

      - name: Run Lint on package
        run: |
          if make lint_package; then
            echo "Lint passed ✅"
          else
            echo "Lint failed ❌"
            exit 1
          fi

      - name: Install unit test dependencies
        run: uv sync --inexact --group test

      - name: Run Lint on tests
        run: |
          if make lint_tests; then
            echo "Test lint passed ✅"
          else
            echo "Test lint failed ❌"
            exit 1
          fi
